services:
  app:
    # Use the image from Docker Hub
    image: kostasmel/oikolog-app:latest
    pull_policy: always
    container_name: oikolog-app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./:/var/www/html:cached
      - ./vendor:/var/www/html/vendor
      - ./node_modules:/var/www/html/node_modules
    environment:
      - APP_ENV=local
      - APP_DEBUG=true
      - APP_KEY=base64:dockerdevkey
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=oikolog
      - DB_USERNAME=root
      - DB_PASSWORD=secret
      - FORCE_MIGRATE=1
    ports:
      - 9000:9000
    depends_on:
      - db

  webserver:
    image: nginx:1.25
    container_name: oikolog-web
    ports:
      - 8000:80
    volumes:
      - ./:/var/www/html:ro
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - app

  db:
    image: mysql:8.1
    container_name: oikolog-db
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=oikolog
    volumes:
      - dbdata:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  dbdata:
